# ---- Base image ----
FROM node:20-alpine

# ---- Set working directory ----
WORKDIR /app

# ---- Copy package files ----
COPY package*.json ./

# ---- Install dependencies ----
RUN npm ci

# ---- Copy source code ----
COPY . .

# ---- Generate Prisma client ----
RUN npx prisma generate

# ---- Build NestJS app ----
RUN npm run build

# ---- Expose port ----
EXPOSE 3000

# ---- Start app ----
CMD ["node", "dist/main.js"]
